USE [GD2C2018]
GO

DROP TABLE ESKHERE.Item_Factura
DROP TABLE ESKHERE.Factura
DROP TABLE ESKHERE.Compra
DROP TABLE ESKHERE.Ubicacion
DROP TABLE ESKHERE.Publicacion
DROP TABLE ESKHERE.Publicacion_Estado
DROP TABLE ESKHERE.Publicacion_Fechas
DROP TABLE ESKHERE.Publicacion_Grado
DROP TABLE ESKHERE.Empresa
DROP TABLE ESKHERE.Rol_X_Funcion
DROP TABLE ESKHERE.Rol_X_Usuario
DROP TABLE ESKHERE.Rol
DROP TABLE ESKHERE.Funcion
DROP TABLE ESKHERE.cliente_premio
DROP TABLE ESKHERE.Premios
DROP TABLE ESKHERE.Puntos
DROP TABLE ESKHERE.Cliente
DROP TABLE ESKHERE.Usuario


