public enum Funcion
{
    ABM_CLIENTE = 1,
    ABM_EMPRESA = 2,
    ABM_GRADO = 3,
    CANJE_DE_PUNTOS = 4,
    COMPRAR = 5,
    EDITAR_PUBLICACION = 6,
    GENERAR_PUBLICACION = 7,
    GENERAR_RENDICION_COMISIONES = 8,
    HISTORIAL_COMPRAS = 9,
    LISTADO_ESTADISTICO = 10
}